name: release-composition-artifact

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: "tag of the repo"
        required: false

jobs:
  release-composition-artifact:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      # with:
      #   ref: 1.0.0
    # - name: determine tag
    #   id: get_tag
    #   run: |
    #     echo "$GITHUB_REF"
    #     # if [[ -n "$GITHUB_REF" ]]; then
    #     #   # Extract tag name from GITHUB_REF (refs/tags/tag_name)
    #     #   TAG_NAME=$(echo "$GITHUB_REF" | sed 's/refs\/tags\///')
    #     # else
    #     #   # Use the manually provided tag, if available
    #     #   TAG_NAME="${{ github.event.inputs.tag_name }}"
    #     # fi
    #     # echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Build
      run: echo $(git describe --tags) > Release.yaml
    - name: Test
      run: cat Release.yaml
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   # if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: Release.txt
    #     token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: google-github-actions/release-please-action@v3
      with:
        release-type: simple
        extra-files: Release.yaml
        token: ${{ secrets.GITHUB_TOKEN }}